# Generated by Django 3.2 on 2024-10-14 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhdenial',
            name='statusOrderDenial',
            field=models.PositiveSmallIntegerField(default=1, help_text='1 - новый, 2 - выгружен в портал', verbose_name='Статус состояния отправки причины неудачи'),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='vat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ставка НДС(%)'),
        ),
    ]
