# Generated by Django 3.2 on 2024-10-11 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_alter_productstock_stock'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payform',
            options={'ordering': ('payFormName',), 'verbose_name': 'форма оплаты(тип цен)', 'verbose_name_plural': 'Формы оплаты(типов цен)'},
        ),
        migrations.AlterField(
            model_name='deliverydate',
            name='minSum',
            field=models.FloatField(blank=True, default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Минимальная сумма заказа'),
        ),
        migrations.AlterField(
            model_name='outletpayform',
            name='warehouse',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payforms_outlet', to='warehouses.warehouse', verbose_name='склад'),
        ),
        migrations.AlterField(
            model_name='payform',
            name='payFormExternalCode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Внешний код формы оплаты'),
        ),
        migrations.AlterField(
            model_name='payform',
            name='payFormName',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название формы оплаты'),
        ),
    ]
