# Generated by Django 3.2 on 2024-11-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_pricelist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[('1', 'Получен'), ('2', 'Отправлен в Б24'), ('3', 'Подтвержден в Выбирай'), ('4', 'Отгружен')], default='1', verbose_name='Статус'),
        ),
    ]
