# Generated by Django 3.2 on 2024-11-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isReturn',
            field=models.BooleanField(default=False, verbose_name='Признак накладной по возврату тары'),
        ),
    ]
