# Generated by Django 3.2 on 2024-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_isreturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='oLCardType',
            new_name='olCardType',
        ),
        migrations.RemoveField(
            model_name='orderhdenial',
            name='statusOrderDenial',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Получен'), (2, 'Отправлен в Б24'), (3, 'Подтвержден в Выбирай'), (4, 'Отгружен')], default=1, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='SyncOrder',
        ),
    ]
