# Generated by Django 3.2 on 2024-10-11 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20241011_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhdenial',
            name='denial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_denial', to='orders.denial', verbose_name='причина отказа'),
        ),
        migrations.AddConstraint(
            model_name='orderdetail',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_order_product'),
        ),
    ]
