# Generated by Django 3.2 on 2024-11-17 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20241117_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code_B24',
            field=models.PositiveSmallIntegerField(default=None, null=True, unique=True, verbose_name='Код Битрикс'),
        ),
    ]
