# Generated by Django 3.2 on 2024-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_code_b24'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isReturn',
            field=models.SmallIntegerField(verbose_name='Признак накладной по возврату тары'),
        ),
    ]
