# Generated by Django 3.2 on 2024-11-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_isreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='isReturn',
            field=models.SmallIntegerField(verbose_name='Признак накладной по возврату тары'),
        ),
    ]
