# Generated by Django 3.2 on 2024-11-19 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_isreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='isReturn',
        ),
    ]
