# Generated by Django 3.2 on 2024-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_isreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_B24',
            field=models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Код Битрикс'),
        ),
    ]
