# Generated by Django 3.2 on 2024-11-20 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_order_code_b24'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=50, unique=True, verbose_name='ИНН')),
                ('legalName', models.CharField(blank=True, max_length=255, verbose_name='Юридическое название')),
                ('code_B24', models.PositiveIntegerField(default=None, null=True, unique=True, verbose_name='Код Битрикс')),
            ],
            options={
                'verbose_name': 'компания',
                'verbose_name_plural': 'Компании',
                'ordering': ('inn',),
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Получен'), (2, 'Отправлен в Б24'), (3, 'Подтвержден в Выбирай'), (4, 'Отгружен'), (5, 'Отгружен в Выбирай')], default=1, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='OutletData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempOutletCode', models.CharField(max_length=50, unique=True, verbose_name='Временный внешний код ТТ')),
                ('deliveryAddress', models.CharField(blank=True, max_length=255, verbose_name='Адрес доставки')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('contactPerson', models.CharField(blank=True, max_length=255, verbose_name='Контактное лицо')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.company', verbose_name='Компания')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'компания в заказе',
                'verbose_name_plural': 'Компания в заказах',
                'ordering': ('tempOutletCode',),
            },
        ),
    ]
