# Generated by Django 3.2 on 2024-12-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20241121_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tempOutletCode',
            field=models.CharField(default='', max_length=50, verbose_name='Временный внешний код ТТ'),
            preserve_default=False,
        ),
    ]
