# Generated by Django 3.2 on 2024-12-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20241202_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Получен'), (2, 'Получен код УС'), (3, 'Отправлен код УС')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='realExternalCode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Код в УС'),
        ),
    ]
