# Generated by Django 3.2 on 2024-12-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_auto_20241204_0113'),
        ('orders', '0018_auto_20241204_0113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operationoutlet',
            options={'ordering': ('outlet', 'operation'), 'verbose_name': 'операция по торговой точке', 'verbose_name_plural': 'Операции по торговым точкам'},
        ),
        migrations.RemoveConstraint(
            model_name='operationoutlet',
            name='unique_warehouse_operation',
        ),
        migrations.RemoveField(
            model_name='operationoutlet',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='operationoutlet',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations_outlet', to='warehouses.outlet', verbose_name='ТТ'),
        ),
        migrations.AddConstraint(
            model_name='operationoutlet',
            constraint=models.UniqueConstraint(fields=('outlet', 'operation'), name='unique_outlet_operation'),
        ),
    ]
