# Generated by Django 3.2 on 2024-12-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_auto_20241204_0113'),
        ('orders', '0019_auto_20241204_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverydate',
            options={'ordering': ('outlet',), 'verbose_name': 'дни доставки и мин сумма', 'verbose_name_plural': 'Дни доставки и мин суммы'},
        ),
        migrations.RemoveField(
            model_name='deliverydate',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='outletpayform',
            name='warehouse',
        ),
        migrations.AddField(
            model_name='deliverydate',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliverydates_outlet', to='warehouses.outlet', verbose_name='ТТ'),
        ),
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='warehouses.outlet', verbose_name='ТТ'),
        ),
        migrations.AddField(
            model_name='outletpayform',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outlet_payforms', to='warehouses.outlet', verbose_name='ТТ'),
        ),
    ]
