# Generated by Django 3.2 on 2024-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20241204_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Получен'), (2, 'Отправлен в Б24'), (3, 'Подтвержден в Выбирай'), (4, 'Отгружен'), (5, 'Отгружен в Выбирай'), (6, 'Выгружен не полностью')], default=1, verbose_name='Статус'),
        ),
    ]
