# Generated by Django 3.2 on 2024-10-10 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictograph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pictograph', models.PositiveSmallIntegerField(verbose_name='Пиктограмма')),
                ('pictographName', models.CharField(max_length=100, verbose_name='Намименование пиктограммы')),
            ],
            options={
                'verbose_name': 'пиктограмма',
                'verbose_name_plural': 'Пиктограммы',
                'ordering': ('pictographName',),
            },
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'ordering': ('packageName',), 'verbose_name': 'тип единицы измерения', 'verbose_name_plural': 'Типы единиц измерения'},
        ),
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.package', verbose_name='Тип единицы измерения'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pictograph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.pictograph', verbose_name='Пиктограмма'),
        ),
    ]
