# Generated by Django 3.2 on 2024-10-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='package',
            field=models.ForeignKey(help_text='Тип единицы измерения(например: бутылка или банка или кег)', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.package', verbose_name='Тип единицы измерения'),
        ),
    ]
