# Generated by Django 3.2 on 2024-11-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(help_text='Наименование для выгрузки в Выбирай', max_length=150, unique=True, verbose_name='Наименование в Выбирай'),
        ),
    ]
