# Generated by Django 3.2 on 2024-10-10 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241010_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictograph',
            name='pictographName',
            field=models.CharField(max_length=100, verbose_name='Наименование пиктограммы'),
        ),
        migrations.AlterField(
            model_name='productattributvalue',
            name='attributValue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribut_values', to='products.attributvalue', verbose_name='Значение атрибута'),
        ),
        migrations.AlterField(
            model_name='productattributvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribut_values', to='products.product', verbose_name='Товар'),
        ),
    ]
