# Generated by Django 3.2 on 2024-11-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codeBitrix',
            field=models.PositiveIntegerField(default=0, verbose_name='Код Битрикс'),
        ),
    ]
