# Generated by Django 3.2 on 2024-11-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_codebitrix'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_code',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Код единицы измерения'),
        ),
    ]
