# Generated by Django 3.2 on 2024-10-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstock',
            options={'ordering': ('warehouse', 'product'), 'verbose_name': 'остатки товаров на складах', 'verbose_name_plural': 'Остатки товаров на складах'},
        ),
    ]
