# Generated by Django 3.2 on 2024-10-11 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='stock',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Остаток на складе'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='customerExternalCode',
            field=models.CharField(help_text='Если точка синхронизации не используется, равно warehouseExternalCode', max_length=50, unique=True, verbose_name='Внешний код точки синхронизации'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_warehouse_product'),
        ),
    ]
