# Generated by Django 3.2 on 2024-10-11 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_auto_20241011_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstock',
            name='stock',
            field=models.FloatField(help_text='Необходимость передачи нулевого значения зависит от: processingType = 0 – можно не передавать processingType = 1 – нужно передавать', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Остаток на складе'),
        ),
    ]
