# Generated by Django 3.2 on 2024-12-04 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_auto_20241204_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outlets', to='warehouses.warehouse', verbose_name='склад'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='allowTareReturn',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Признак возврата тары: 1-да, 0-нет'),
        ),
    ]
