# Generated by Django 3.2 on 2024-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0007_auto_20241204_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outlet',
            name='realExternalCode',
        ),
        migrations.AlterField(
            model_name='outlet',
            name='outletName',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование ТТ в 1С'),
        ),
    ]
