# Generated by Django 3.2 on 2024-12-04 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_auto_20241204_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='code_B24',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Код Битрикс'),
        ),
    ]
