# Generated by Django 3.2 on 2024-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_alter_outlet_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ('outletName',), 'verbose_name': 'компания', 'verbose_name_plural': '\u200bКомпании'},
        ),
        migrations.AlterModelOptions(
            name='productstock',
            options={'ordering': ('warehouse', 'product'), 'verbose_name': 'остатки товаров на складах', 'verbose_name_plural': '\u200b\u200bОстатки товаров на складах'},
        ),
        migrations.AlterField(
            model_name='outlet',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Получен'), (2, 'Получен код УС'), (3, 'Отправлен код в Выбирай'), (5, 'Данные отправлены в Выбирай'), (4, 'Отменён в Выбирай')], default=1, verbose_name='Статус'),
        ),
    ]
